### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [52]:
import random
import numpy as np

In [53]:
vector = np.random.rand(10,)

display("vector:", vector, "shape:", vector.shape)

'vector:'

array([0.77865277, 0.62336953, 0.51038686, 0.19017654, 0.75161847,
       0.24218213, 0.01102473, 0.85780059, 0.18701832, 0.25012387])

'shape:'

(10,)

In [54]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

display("matrix:", matrix, "shape:", matrix.shape)

'matrix:'

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

'shape:'

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [55]:
vector = (vector * 10).round(2)
vector

array([7.79, 6.23, 5.1 , 1.9 , 7.52, 2.42, 0.11, 8.58, 1.87, 2.5 ])

In [56]:
matrix = matrix * 2
matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [57]:
vector_sq = vector ** 2
vector_sq

array([6.06841e+01, 3.88129e+01, 2.60100e+01, 3.61000e+00, 5.65504e+01,
       5.85640e+00, 1.21000e-02, 7.36164e+01, 3.49690e+00, 6.25000e+00])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [58]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [59]:
# B x A
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [60]:
# result_matrix x C
result_C = np.dot(result_matrix, C)
result_C

array([[0.5202],
       [0.2846]])

In [61]:
# result_matrix x D
result_D = np.dot(result_matrix, D)
result_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [62]:
# Транспонована матриця
result_matrix_T = result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [63]:
# Транспонований вектор
vector_T = vector.T

print(vector, vector.shape)
print(vector_T, vector_T.shape)

[7.79 6.23 5.1  1.9  7.52 2.42 0.11 8.58 1.87 2.5 ] (10,)
[7.79 6.23 5.1  1.9  7.52 2.42 0.11 8.58 1.87 2.5 ] (10,)


Різниці між оригінальним і транспонованим векторами не бачу. 

In [64]:
# Expand dimensions
column_vector = np.expand_dims(vector, axis=1)

print(vector, vector.shape)
print(column_vector, column_vector.shape)

[7.79 6.23 5.1  1.9  7.52 2.42 0.11 8.58 1.87 2.5 ] (10,)
[[7.79]
 [6.23]
 [5.1 ]
 [1.9 ]
 [7.52]
 [2.42]
 [0.11]
 [8.58]
 [1.87]
 [2.5 ]] (10, 1)


Тут вже видно різницю. Оригінальний вектор має розмірність 1х10, а утворений - 10х1.

In [65]:
# Транспонований вектор-стовпець
column_vector_T = column_vector.T

print(column_vector_T, column_vector_T.shape)

[[7.79 6.23 5.1  1.9  7.52 2.42 0.11 8.58 1.87 2.5 ]] (1, 10)
