# HW7. Numpy

### 1. Створення масивів

In [51]:
import numpy as np

In [52]:
print(np.array([5, 15, 25, 35, 45]))
print(np.zeros(7))
print(np.ones(6))
print(np.arange(10, 20))

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]


### 2. Базові операції

In [53]:
my_array = np.array([12, 24, 36, 48, 60])
display(my_array)

array([12, 24, 36, 48, 60])

In [54]:
print(my_array * 2)
print(my_array + 10)
print(my_array ** 2)
print(np.sqrt(my_array))

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]


### 3. Статистичні функції

In [55]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
display(data)

array([18, 27, 33, 41, 52, 68, 79])

In [56]:
print(data.mean())
print(data.min())
print(data.max())
print(data.sum())

45.42857142857143
18
79
318


### 4. Індексація

In [57]:
arr = np.array([15, 22, 35, 44, 58, 67])
display(arr)

array([15, 22, 35, 44, 58, 67])

In [58]:
print(arr[0])
print(arr[-1])
print(arr[1:4])

mask = arr > 40
print(arr[mask])

15
67
[22 35 44]
[44 58 67]


### 5. Двовимірні масиви

In [59]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
display(matrix)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [60]:
print(matrix.shape)
print(matrix[0, :])
print(matrix[:, 1])
print(matrix.sum())
print(matrix.mean())

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
